### ISSUE TITLE
US 01.06.01 Entrant views app details when scanning QR code

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#14]
As an entrant I want to view event details within the app by scanning the promotional QR code

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/5054763a-fc24-41be-80ac-b2edf9f3a5ed)
I'm going to change this to be instead an events section with a button to open the scanner, then when it scans it will lead to the events page in the app showing the details
