### ISSUE TITLE
US 01.06.02 Entrant can sign up to events by scanning QR code

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#15]
As an entrant I want to be able to be sign up for an event by scanning the QR code

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/c8299566-bd4c-4714-8d44-f086f724881e)
This was the original mockup, but for entrants, we should have just a button for a scanner rather than a search bar
