### ISSUE TITLE
US 02.01.01 Organizer can create new event and generate QR code

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#17]
As an organizer I want to create a new event and generate a unique promotional QR code that links to the event description and event poster in the app

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/76d06c73-47b7-4e13-93ac-84f3c43649a2)

**Comment by gwen-dls** [comment]
Make sure to add a back button
