### ISSUE TITLE
US 02.06.04 organizer cancels entrants

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#31]
As an organizer I want to cancel entrants that did not sign up for the event

**Comment by gwen-dls** [comment]
Working in the lottery branch, OrganizerEntrantActivity class. Adding on to cancelled entrant

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/ca15408d-6c8f-4193-8f77-fc9a07ebf0ac)

**Comment by gwen-dls** [comment]
This isn't working within the app and the firebase
