### ISSUE TITLE
US 03.03.01 Administrator can remove images (profile pictures/posters)

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#37]
As an administrator, I want to be able to remove images

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/077923b2-1d9e-4973-bd73-47b503a09e87)

**Comment by gwen-dls** [comment]
Should split this into:
- remove profile pictures
- remove event posters
