### ISSUE TITLE
US 03.03.02 Administrator can remove hashed QR code data

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#38]
As an administrator, I want to be able to remove hashed QR code data

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/3ef21edb-521e-4023-9cea-7f8cba6367fa)

**Comment by gwen-dls** [comment]
Does this mean removing events? Maybe the QR code just doesn't exist or when scanned, the event is closed?
