### ISSUE TITLE
US 03.07.01 Administrator can remove facilities that violate app policy

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#42]
As an administrator I want to remove facilities that violate app policy

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/ef36f053-604b-42d1-ae56-371b43d9a5c9)

**Comment by gwen-dls** [comment]
Gotta wait to see facility format. Is facility gonna be it's own section like "entrants" and "events"
