### ISSUE TITLE
US 01.03.03 Entrant profile picture can be deterministically generated from profile name

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#7]
As an entrant I want my profile picture to be deterministically generated from my profile name if I haven't uploaded a profile image yet.

**Comment by gwen-dls** [comment]
Recommended: Deterministically generate pfp based on first letter of name? So A instead of apple

![Image](https://github.com/user-attachments/assets/c4a6df3c-d5c8-41d4-9fff-bb3b61ea98af)
