### ISSUE TITLE
Events Issues

### ISSUE THREAD

**Issue by ChesterLuna** [CMPUT301F24bubble/bubbletracks#75]
Make some sections optional.
For the non optional sections we should add a toast telling people to fill it up.

**Comment by greenpicat** [comment]
Have to close and open* app after creating an event to see it under hosted events

*or possibly just switch activities?

**Comment by greenpicat** [comment]
Also, very low priority but I don't think its clear how to open the calendar window when selecting the start and end dates, since they have a lock icon.

**Comment by ChesterLuna** [comment]
100% agree @greenpicat
