### ISSUE TITLE
US 01.04.01 entrant receives notif

### ISSUE THREAD

**Issue by sgctcub** [CMPUT301F24bubble/bubbletracks#8]
As an entrant I want to receive notification when chosen from the waiting list (when I "win" the lottery)

**Comment by gwen-dls** [comment]
![Image](https://github.com/user-attachments/assets/10077a12-d31f-4bd7-872e-87bbae248cf9)
![Image](https://github.com/user-attachments/assets/d0f9576b-d089-4c1c-9470-80a7faa83a65)
